### ISSUE TITLE
New list

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#18]
Been silly busy at work, but I'll just leave these here...

`263:10:34` `presumatly` -> "presumably"

`263:23:24` `about one-half foot` doesn't he say "about half a foot per second"

`263:38:59` `right.now.` -> "right now."

`264:37:02` `the data, replayed` imo he says it without the comma, what do you think?

`265:17:54` `erase-able` is that correct English? I'd go without the dash/hyphen, and
`in effect, make a decision` is also something I'm not sure about, being non-native and all

`267:36:25` `BAT` I'm sure they talked about "BATT" before, but this is (like some of the above)
might not be OCR mistakes but just another typist doing things different.

`274:58:02` `wakeup` -> "wakeup."

`276:28:01` `-it's convenient` -> "- it's convenient" (space after the dash)

`280:05:53` `SC` again?

`280:25:28` `is that` -> "Is that" (new sentence)

**Comment by bfeist** [comment]
Thanks again! On some of the grammar: 265:17:54 erase-able was probably a new word back then, now with computers prevalent it's erasable. Changed. The comma after in effect is correct, I added it to the other sentence in that utterance with "in effect". "wakeup" should be "wake-up" because it's an action being turned into a noun. Thanks for the SC catch. That's obviously Evans. The others were all great catches.
