### ISSUE TITLE
Question about overlapping sound/transcript

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#8]
`112:36` and onwards for example, as a general question, there have been Public Affairs utterances that go over something in the transcript, and then that talk kicks in. Is this in the original material and your choice to have only one soundtrack or is this configurable somewhere or what gives?

Thanks!

**Comment by bfeist** [comment]
That's an error in the original recording. Other times there's crosstalk because they replayed segments of the mission that occurred during press briefings. I wish I could get a hold of the press briefings to include.

The digitized recordings have the PAO talking over top of the transmissions. The original TEC transmissions must exist somewhere though, because they were transcribed in 1973. They're in an archive somewhere.
